name: "CD - Networking"

on:
  push:
    branches:
      - main
    path:
      - ".github/**"
      - "networking/**"
jobs:
  validate:
    uses: ./.github/workflows/validate.yaml
    with:
      target: "networking/Irrelephant.Outcast.Networking.sln"

  publish:
    needs: validate
    uses: ./.github/workflows/nuget.publish.yaml
    with:
      target: "networking/Irrelephant.Outcast.Networking.sln"
      version: "0.0.${{ github.run_number }}"