name: "CD - Server"

on:
  push:
    branches:
      - main
    path:
      - ".github/**"
      - "server/**"

jobs:
  publish:
    uses: ./.github/workflows/nuget.publish.yaml
    with:
      target: "server/Irrelephant.Outcast.Server.sln"
      version: "0.0.${{ github.run_number }}"