name: "CI"

on:
  pull_request:
    path:
      - ".github/**"
      - "protocol/**"

jobs:
  validate:
    name: "Check Build"
    uses: ./.github/workflows/validate.yaml
    with:
      target: "protocol/Irrelephant.Outcast.Protocol.sln"