name: "CI"

on:
  pull_request:
    path:
      - ".github/**"
      - "networking/**"

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml
    with:
      target: "server/Irrelephant.Outcast.Server.sln"