name: Build & Publish

on:
  workflow_call:
    inputs:
      target:
        description: 'Solution to Validate'
        required: true
        type: string

      configuration:
        description: 'Configuration of the Build'
        required: false
        default: 'Release'
        type: string

      version:
        description: 'Version of the package to Publish'
        required: true
        type: string

jobs:
  check:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version:
            - '9.0.x'
            - '8.0.x'

      - run: dotnet restore --locked-mode ${{ inputs.target }}

      - run: |
          dotnet build \
            --no-restore \
            --configuration=${{ inputs.configuration }} \
            ${{ inputs.target }}

      - run: |
          dotnet pack \
            --no-build \
            /p:Version=${{ inputs.version }} \
            ${{ inputs.target }}

      - run: |
          for file in $(find . -name \*.nupkg); do
            dotnet nuget push --api-key="${{ secrets.GITHUB_TOKEN }}" $file
          done
