name: Build & Publish

on:
  workflow_call:
    inputs:
      target:
        description: 'Solution to Validate'
        required: true
        type: string

      configuration:
        description: 'Configuration of the Build'
        required: false
        default: 'Release'
        type: string

      version:
        description: 'Version of the package to Publish'
        required: true
        type: string

jobs:
  check:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x

      - name: dotnet restore
        run: dotnet restore --locked-mode ${{ inputs.target }}


      - name: dotnet build
        run: |
          dotnet build \
            --configuration=${{ inputs.configuration }} \
            ${{ inputs.target }}
        env:
          NuGetPackageSourceCredentials_Irrelepant: Username=${{ github.actor }};Password=${{ secrets.GITHUB_TOKEN }}
      
      - name: dotnet pack
        run: |
          dotnet pack \
            --no-build \
            /p:Version=${{ inputs.version }} \
            ${{ inputs.target }}

      - name: dotnet nuget push
        run: |
          for file in $(find . -name \*.nupkg); do
            dotnet nuget push --api-key="${{ secrets.GITHUB_TOKEN }}" $file
          done
