name: Publish

on:
  workflow_call:
    inputs:
      target:
        description: 'Solution to Validate'
        required: true
        type: string
      configuration:
        description: 'Configuration of the Build'
        required: false
        default: 'Release'
        type: string

jobs:
  check:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - run: dotnet restore --locked-mode ${{ inputs.target }}

      - run: dotnet build --configuration=${{ inputs.configuration }} ${{ inputs.target }}

      - run: dotnet pack --configuration=${{ inputs.configuration }} ${{ inputs.target }}

      - run: |
          dotnet nuget push \
            --source="Irrelephant Github
            --api-key=${{ secrets.GITHUB_TOKEN }}
            "protocol/src/Irrelephant.Outcast.Protocol.Abstractions/bin/Release/Irrelephant.Outcast.Protocol.Abstractions.1.0.0.nupkg" \
