name: Validate

on:
  workflow_call:
    inputs:
      target:
        description: 'Solution to Validate'
        required: true
        type: string

      configuration:
        description: 'Configuration of the Build'
        required: false
        default: 'Release'
        type: string

jobs:
  check:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x

      - name: dotnet restore
        run: |
          dotnet nuget update source Irrelephant \
            --username=${{ github.actor }} \
            --password=${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

          dotnet restore --locked-mode ${{ inputs.target }}

      - name: dotnet build
        run: |
          dotnet build \
            --no-restore \
            --configuration=${{ inputs.configuration }} \
            ${{ inputs.target }}

      - name: dotnet test
        run: dotnet test --no-build  --configuration=${{ inputs.configuration }} ${{ inputs.target }}