name: Validate

on:
  workflow_call:
    inputs:
      target:
        description: 'Solution to Validate'
        required: true
        type: string

      configuration:
        description: 'Configuration of the Build'
        required: false
        default: 'Release'
        type: string

jobs:
  check:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            - '9.0.x'
            - '8.0.x'

      - run: dotnet restore --locked-mode ${{ inputs.target }}

      - run: dotnet test --no-build ${{ inputs.target }}
